# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cls',
            new_name='Class',
        ),
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='t', max_length=1),
            preserve_default=False,
        ),
    ]
