# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20161208_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ChineseName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='EnglishName',
            field=models.TextField(null=True),
        ),
    ]
