# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20161208_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalassignment',
            name='student',
            field=models.ManyToManyField(blank=True, to='assignment.User'),
        ),
    ]
