# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20161208_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
