# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_auto_20161208_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(blank=True, null=True, to='assignment.Assignment'),
        ),
    ]
