# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_auto_20161208_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalassignment',
            name='assignment',
        ),
        migrations.AddField(
            model_name='personalassignment',
            name='assignment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='personalassignment',
            name='student',
        ),
        migrations.AddField(
            model_name='personalassignment',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assignment.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='user',
            name='Class',
        ),
        migrations.AddField(
            model_name='user',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Class'),
        ),
    ]
