# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_auto_20161208_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Class',
        ),
        migrations.AddField(
            model_name='user',
            name='Class',
            field=models.ManyToManyField(blank=True, null=True, to='assignment.Class'),
        ),
    ]
