# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0015_auto_20161208_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to=b'')),
                ('md5', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(to='assignment.Assignment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Class',
            field=models.ManyToManyField(to='assignment.Class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignments',
            field=models.ManyToManyField(to='assignment.Attachment'),
        ),
    ]
