# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_auto_20161209_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='id',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content',
            field=models.FileField(upload_to=b'Files'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='md5',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
