# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_auto_20161209_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ChineseName',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='EnglishName',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
