# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0019_auto_20161209_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Class',
            field=models.ManyToManyField(blank=True, to='assignment.Class'),
        ),
    ]
