# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0021_auto_20161209_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='assignment.Attachment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
