# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0024_auto_20161209_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2030, 1, 1, 0, 0)),
        ),
    ]
