# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0025_auto_20161209_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='attachments',
            field=models.ManyToManyField(blank=True, default=[], to='assignment.Attachment'),
        ),
        migrations.AlterField(
            model_name='class',
            name='assignments',
            field=models.ManyToManyField(default=[], to='assignment.Assignment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Class',
            field=models.ManyToManyField(blank=True, default=[], to='assignment.Class'),
        ),
    ]
