# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0026_auto_20161209_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='type',
            field=models.SmallIntegerField(choices=[(1, b'assignment'), (2, b'information')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(b's', b'student'), (b't', b'teacher')], max_length=1),
        ),
    ]
